// src/views/doom.vue
<template>
  <div class="screen-root" ref="screenRoot">
    <div class="screen-wrapper" v-bind:class="{ fullscreen: fullscreen }">
      <canvas width="320" height="320" ref="screen">
      </canvas>

      <v-btn icon absolute right bottom @click="toggleFullScreen()">
        <v-icon>
          {{ fullscreen ? 'mdi-fullscreen-exit' : 'mdi-fullscreen' }}
        </v-icon>
      </v-btn>

      <v-snackbar app v-model="displayError">
        {{ error }}
      </v-snackbar>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from 'vue-property-decorator'
import { Doom as RawDoom } from '@/doom/doom'
import { Params } from '@/doom/doom/params'
import { fs } from '@/doom/system/fs'

@Component
export default class Doom extends Vue {
  $refs!: {
    screen: HTMLCanvasElement
    screenRoot: HTMLDivElement
  }

  doomInst!: RawDoom

  private defaultParams!: Params

  async mounted(): Promise<void> {
    const paramsStr = localStorage.getItem('params')
    if (paramsStr !== null) {
      const params = JSON.parse(paramsStr)
      if (params !== null && typeof params === 'object') {
        this.params = params
      }
    }

    await fs.write('doom1.wad', './doom1.wad', false)

    await this.start()

    this.registerFullScreenChange()
  }

  async restart(): Promise<void> {
    await this.doomInst.quit()

    await this.start()

    this.$refs.screen.focus()
  }
  params: Partial<Params> = {}
  async start(): Promise<void> {
    try {
      const screen = this.$refs.screen

      localStorage.setItem('params', JSON.stringify(this.params))

      this.doomInst = new RawDoom({
        screen,
        wad: 'doom1.wad',
        ...this.params,
      })
      this.doomInst.onError = (e) => this.onError(e)

      await this.doomInst.init()

      const ctx = this.doomInst.iSound.audioCtx
      if (ctx) {
        ctx.addEventListener('statechange', e => {
          this.sound = !!ctx && ctx.state === 'running'
          this.$emit('soundChange', this.sound)
        })
      }
    } catch (e) {
      this.onError(e)
    }
  }

  displayError = false
  error = ''
  private onError(e: unknown): void {
    if (e instanceof Error) {
      e = e.message
      console.error(e)
    }

    if (typeof e === 'string') {
      this.error = e
      this.displayError = true
    }
  }

  @Prop() sound = false
  @Watch('sound') setSound(a: boolean): void {
    const ctx = this.doomInst.iSound.audioCtx
    if (ctx === null) {
      return
    }
    if (a) {
      ctx.resume()
    } else {
      ctx.suspend()
    }
  }

  fullscreen = false
  registerFullScreenChange(): void {
    const el = this.$refs.screenRoot
    el.addEventListener('fullscreenchange', () => {
      this.fullscreen = document.fullscreenElement === el
    })
  }
  async toggleFullScreen(): Promise<void> {
    const el = this.$refs.screenRoot
    if (el) {
      if (document.fullscreenElement === el) {
        await document.exitFullscreen()
      } else {
        await el.requestFullscreen()
      }
    }
  }

  beforeDestroy(): void {
    this.doomInst.quit()
  }
}
</script>

<style lang="scss" scoped>
.screen-wrapper {
  width: calc((100vh - 64px) * 4 / 3);
  height: calc(100vh - 64px);

  &.fullscreen {
    width: calc((100vh) * 4 / 3);
    height: calc(100vh);
  }

  margin: 0 auto;
  > canvas {
    width: 100%;
    height: 100%;
    image-rendering: pixelated;
    outline: none;
  }
}
</style>

// src/views/Doom.tsx
import './Doom.css'
import { CSSProperties, useCallback, useEffect, useRef, useState } from 'react';
import { Params } from '../doom/doom/params'
import { Doom as RawDoom } from '../doom/doom'

interface Inputs {
  params?: Partial<Params>,
}

export default function Doom({ params }: Inputs) {
  const [ fullscreen, setFullscreen ] = useState(false)
  const [ ratio, setRatio ] = useState(4/3)

  const screen2dRef = useRef<HTMLCanvasElement>(null)
  const screen3dRef = useRef<HTMLCanvasElement>(null)
  const screenRoot = useRef<HTMLDivElement>(null)

  const doomInstRef = useRef<RawDoom>()

  const start = useCallback(async() => {
    try {
      const screen2d = screen2dRef.current!
      const screen3d = screen3dRef.current!

      const doomInst = new RawDoom({
        input: screen2d,
        screen2d,
        screen3d,
        iwad: 'doom1.wad',
        ...params,
      })
      doomInstRef.current = doomInst

      await doomInst.init()

      setRatio(doomInst.iVideo.ratio)
    } catch (e) {
      console.error(e)
    }
  }, [ params ])

  const stop = useCallback(() => {
    if (doomInstRef.current) {
      doomInstRef.current.quit()
      doomInstRef.current = undefined
    }
  }, [])

  const registerFullScreenChange = useCallback(() => {
    const el = screenRoot.current!
    el.addEventListener('fullscreenchange', () => {
      setFullscreen(document.fullscreenElement === el)
    })
  }, [])

  useEffect(() => {
    start();
    registerFullScreenChange()

    return stop;
  }, [ start, registerFullScreenChange, stop ])

  return (
    <div className="screen-root" ref={screenRoot}>
      <div
        className={`screen-wrapper ${fullscreen ? 'fullscreen' : ''}`}
        style={{ '--ratio': ratio } as CSSProperties}
      >
        <canvas width="320" height="320" ref={screen3dRef}>
        </canvas>
        <canvas width="320" height="320" ref={screen2dRef}>
        </canvas>
      </div>
    </div>
  )
}
